// Generated by CoffeeScript 1.7.1
var barPadding, canvasHeight, canvasWidth, colors, g, isNumeric, labelPadding, margin, state, svg, textHorizontalScale, textSizeScale, textVerticalScale, title, xScale, yScale;

margin = {
  top: 50,
  bottom: 10,
  left: 250,
  right: 40
};

canvasWidth = 1000 - margin.left - margin.right;

canvasHeight = 1000 - margin.top - margin.bottom;

barPadding = 0.05;

labelPadding = -10;

textHorizontalScale = 1.5;

textVerticalScale = 0.77;

textSizeScale = 21.25;

colors = {
  white: "#ffffff",
  blue: "#084594",
  darkGray: "#696969"
};

xScale = d3.scale.linear().range([0, canvasWidth]);

yScale = d3.scale.ordinal().rangeRoundBands([0, canvasHeight], barPadding);

state = function(d) {
  return d.State;
};

isNumeric = function(num) {
  return !isNaN(num);
};

svg = d3.select("body").append("svg").attr("id", "chart").attr("width", canvasWidth + margin.left + margin.right).attr("height", canvasHeight + margin.top + margin.bottom);

g = svg.append("g").attr("transform", "translate(" + margin.left + ", " + margin.top + ")");

title = g.append("text").attr("id", "title").attr("x", svg.attr("width") / 4).attr("text-anchor", "middle").text("Unemployment Rates for States");

d3.tsv("unemp_states_us_nov_2013.tsv", function(data) {
  var ascending, bars, color, groups, labels, max, min, reorder, values;
  min = 0;
  max = d3.max(data, function(d) {
    return d.Rate;
  });
  xScale.domain([min, max]);
  yScale.domain(data.map(state));
  color = d3.scale.linear().domain([min, max]).interpolate(d3.interpolateRgb).range([colors.white, colors.blue]);
  groups = g.append("g").selectAll("g").data(data).enter().append("g").attr("transform", function(d) {
    return "translate(0, " + (yScale(d.State)) + ")";
  });
  bars = groups.append("rect").attr("width", function(d) {
    return xScale(d.Rate);
  }).attr("height", yScale.rangeBand()).attr("fill", function(d) {
    return color(d.Rate);
  });
  labels = groups.append("text").attr("x", labelPadding).attr("y", yScale.rangeBand() * textVerticalScale).attr("font-size", "" + (yScale.rangeBand() / textSizeScale) + "em").attr("text-anchor", "end").text(function(d) {
    return d.State;
  });
  values = groups.append("text").attr("x", function(d) {
    return xScale(d.Rate) - yScale.rangeBand() * textHorizontalScale;
  }).attr("y", yScale.rangeBand() * textVerticalScale).attr("font-size", "" + (yScale.rangeBand() / textSizeScale) + "em").attr("fill", "white").attr("text-anchor", "start").text(function(d) {
    return d.Rate;
  });
  ascending = false;
  reorder = function(key) {
    ascending = !ascending;
    data = data.sort(function(a, b) {
      var aTieBreaker, bTieBreaker, valueA, valueB, verdict;
      valueA = a[key];
      valueB = b[key];
      if (isNumeric(valueA) && isNumeric(valueB)) {
        valueA = +valueA;
        valueB = +valueB;
      }
      if (ascending) {
        verdict = d3.ascending(valueA, valueB);
        if (verdict === 0) {
          aTieBreaker = a.State.toLowerCase();
          bTieBreaker = b.State.toLowerCase();
          if (aTieBreaker < bTieBreaker) {
            return -1;
          } else if (aTieBreaker > bTieBreaker) {
            return 1;
          } else {
            return 0;
          }
        } else {
          return verdict;
        }
      } else {
        verdict = d3.descending(valueA, valueB);
        if (verdict === 0) {
          aTieBreaker = a.State.toLowerCase();
          bTieBreaker = b.State.toLowerCase();
          if (aTieBreaker > bTieBreaker) {
            return -1;
          } else if (aTieBreaker < bTieBreaker) {
            return 1;
          } else {
            return 0;
          }
        } else {
          return verdict;
        }
      }
    });
    yScale.domain(data.map(state));
    return groups.transition().duration(1000).delay(function(d, i) {
      return i * 25;
    }).attr("transform", function(d, i) {
      return "translate(0, " + (yScale(d.State)) + ")";
    });
  };
  reorder("Rate");
  d3.selectAll("input").on("click", function() {
    return reorder(this.value);
  });
  bars.on("mouseover", function() {
    return d3.select(this).attr("fill", colors.darkGray);
  });
  return bars.on("mouseout", function() {
    return d3.select(this).transition().duration(250).attr("fill", function(d) {
      return color(d.Rate);
    });
  });
});
