// Generated by CoffeeScript 1.7.1
var barHeight, canvasHeight, canvasWidth, g, margin, state, svg, xScale, yScale;

margin = {
  top: 50,
  bottom: 10,
  left: 300,
  right: 40
};

canvasWidth = 900 - margin.left - margin.right;

canvasHeight = 900 - margin.top - margin.bottom;

xScale = d3.scale.linear().range([0, canvasWidth]);

yScale = d3.scale.ordinal().rangeRoundBands([0, canvasHeight], .8, 0);

barHeight = 15;

state = function(d) {
  return d.State;
};

svg = d3.select("body").append("svg").attr("width", canvasWidth + margin.left + margin.right).attr("height", canvasHeight + margin.top + margin.bottom);

g = svg.append("g").attr("transform", "translate(" + margin.left + ", " + margin.top + ")");

d3.tsv("unemp_states_us_nov_2013.tsv", function(data) {
  var bars, groups, max, min;
  max = d3.max(data, function(d) {
    return d.Rate;
  });
  min = 0;
  xScale.domain([min, max]);
  yScale.domain(data.map(state));
  groups = g.append("g").selectAll("g").data(data).enter().append("g").attr("transform", function(d, i) {
    return "translate(0, " + (yScale(d.State)) + ")";
  });
  return bars = groups.append("rect").attr("width", function(d) {
    return xScale(d.Rate);
  }).attr("height", barHeight);
});
