// Generated by CoffeeScript 1.7.1
d3.text("unemp_states_us_nov_2013.tsv", function(error, data) {
  var dataCells, dataset, header, headerCells, rows, tBody, tHead, table;
  d3.select("body").append("h1").text("Unemployment Rates for States");
  table = d3.select("body").append("table");
  tHead = table.append("thead");
  tBody = table.append("tbody");
  table.append("caption").attr("class", "upper").html("Unemployment Rates for States<br>Monthly Rankings<br>Seasonally Adjusted<br>Dec. 2013<sup>p</sup>");
  table.append("caption").attr("class", "lower").html("<sup>p</sup> = preliminary");
  dataset = [];
  d3.tsv.parseRows(data, function(row) {
    return dataset.push({
      "Rank": row[0],
      "State": row[1],
      "Rate": row[2]
    });
  });
  header = tHead.selectAll("tr").data(dataset.slice(0, 1)).enter().append("tr");
  rows = tBody.selectAll("tr").data(dataset.slice(1)).enter().append("tr").style("background-color", function(d, i) {
    if (i % 2 === 0) {
      return "#f1f1f1";
    } else {
      return "#ffffff";
    }
  });
  headerCells = header.selectAll("th").data(function(row) {
    var key, _results;
    _results = [];
    for (key in row) {
      _results.push(row[key]);
    }
    return _results;
  }).enter().append("th").text(function(d) {
    return d;
  });
  dataCells = rows.selectAll("td").data(function(row) {
    var key, _results;
    _results = [];
    for (key in row) {
      _results.push(row[key]);
    }
    return _results;
  }).enter().append("td").attr("class", function(d, i) {
    return "column-" + i;
  }).text(function(d) {
    return d;
  });
  dataCells.on("mouseover", function(d, i) {
    d3.select(this.parentNode).style("background-color", "#ffff99");
    return d3.selectAll(".column-" + i).style("background-color", "#ffff99");
  });
  return dataCells.on("mouseout", function(d, i) {
    rows.style("background-color", function(d, i) {
      if (i % 2 === 0) {
        return "#f1f1f1";
      } else {
        return "#ffffff";
      }
    });
    return d3.selectAll(".column-" + i).style("background-color", null);
  });
});
